### ISSUE TITLE
error: cannot find macro `asm` in this scope

### ISSUE THREAD

**Issue by srpulpo-crypto** [fortanix/rust-sgx#389] opened 2022-02-28 13:22 UTC
When I try  to install (_cargo +nightly install sgxs-tools_) I have the next errors:

_error: cannot find macro `asm` in this scope
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/enclave-runner-0.5.0/src/tcs.rs:66:13
   |
66 |             asm!("
   |             ^^^
   |
   = note: consider importing one of these items:
           crate::tcs::std::arch::asm
           std::arch::asm
           core::arch::asm

error: cannot find macro `asm` in this scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/enclave-runner-0.5.0/src/tcs.rs:139:13
    |
139 |             asm!("
    |             ^^^
    |
    = note: consider importing one of these items:
            crate::tcs::std::arch::asm
            std::arch::asm
            core::arch::asm

error: cannot find macro `asm` in this scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/enclave-runner-0.5.0/src/tcs.rs:185:13
    |
185 |             asm!("
    |             ^^^
    |
    = note: consider importing one of these items:
            crate::tcs::std::arch::asm
            std::arch::asm
            core::arch::asm

error: cannot find macro `asm` in this scope
    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/enclave-runner-0.5.0/src/usercalls/mod.rs:1229:9
     |
1229 |         asm!("
     |         ^^^
     |
     = note: consider importing one of these items:
             std::arch::asm
             core::arch::asm

error: could not compile `enclave-runner` due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `sgxs-tools v0.8.5`, intermediate artifacts can be found at `/tmp/cargo-installmdhchn`

Caused by:
  build failed_

**Comment by jethrogb** [comment] 2022-02-28 14:51
Duplicate of #374

**Closed by jethrogb** 2022-02-28 14:51 UTC
