### ISSUE TITLE
Support for Linux in-tree SGX driver

### ISSUE THREAD

**Issue by Jaakkonen** [fortanix/rust-sgx#305] opened 2020-12-25 17:22 UTC
There's now ready mainline SGX driver for Linux kernel [here](https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/log/?h=x86/sgx). The driver will probably be merged to kernel 5.11 coming next spring.
The Intel linux-sgx sdk should support it out of the box if only using `enclave_common` interfaces.
There's guides on converting SGX remote attestation software to the new driver [here](https://github.com/intel/SGXDataCenterAttestationPrimitives/pull/141).

Currently at least `sgx-detect` tool checks directly `isgx` driver. 
[Documentation](https://git.kernel.org/pub/scm/linux/kernel/git/tip/tip.git/tree/Documentation/x86/sgx.rst?h=x86/sgx) for the new driver in the kernel branch.

**Comment by jethrogb** [comment] 2020-12-27 09:42
Duplicate of #181

**Closed by jethrogb** 2020-12-27 09:42 UTC
