### ISSUE TITLE
SGXv2

### ISSUE THREAD

**Issue by MoSalemIb** [fortanix/rust-sgx#452] opened 2023-05-22 11:20 UTC
The initial Intel SGX platform was very restrictive on enclaves. At compile time the developer needed to define the number of threads and heap and stack sizes. They could not be changed afterwards. This is no longer the case for SGXv2; both memory and threads can be added dynamically. Development on this was more or less complete 3 years ago, but code never got reviewed.

1. Dynamically adding heap space
[Rust Repo](https://github.com/fortanix/rust/tree/raoul/edmm)

2. Dynamically adding new SGX hardware threads
[Personal Repo](https://github.com/raoulstrackx/rust/tree/raoul/dyn_tcs)

3.Dynamically adding stack space (may need new entry code)

**Comment by raoulstrackx** [comment] 2023-06-12 07:33
duplicate of #104

**Closed** 2023-06-12 07:37 UTC
Labels: std/rustc, Intel SGX
